
drop table a_tracker_project if exists;

drop table a_tracker_issue if exists;

create table a_tracker_project (
    id bigint generated by default as identity(start with 1, increment by 1),
    name varchar(100),
    summary varchar(6000),
    constraint pk_tracker_project primary key(id)
);


create table a_tracker_issue (
    id bigint generated by default as identity(start with 1, increment by 1),
    project_id bigint,
    name varchar(50),
    priority int,
    severity int,
    status int,
    assign_to varchar(50),
    submit_by varchar(50),
    add_time datetime,
    update_date datetime,
    content varchar(6000),
    file varchar(100),
    constraint pk_tracker_issue primary key(id),
    constraint fk_tracker_issue_project_id foreign key(project_id) references a_tracker_project(id)
);

