
drop table a_news_config if exists;

drop table a_news_category if exists;

drop table a_news if exists;

drop table a_news_comment if exists;

drop table a_news_tag if exists;

drop table a_news_newstag if exists;

create table a_news_config (
    id bigint generated by default as identity(start with 1, increment by 1),
    news_need_audit int,
    comment_need_audit int,
    could_comment int,
    constraint pk_news_config primary key(id)
);


create table a_news_category (
    id bigint generated by default as identity(start with 1, increment by 1),
    parent_id bigint,
    top_id bigint,
    name varchar(50),
    the_sort int,
    status int,
    constraint pk_news_category primary key(id),
    constraint fk_news_category_top_id foreign key(top_id) references a_news_category(id),
    constraint fk_news_category_parent_id foreign key(parent_id) references a_news_category(id)
);


create table a_news (
    id bigint generated by default as identity(start with 1, increment by 1),
    category_id bigint,
    name varchar(100),
    subtitle varchar(100),
    link varchar(100),
    image varchar(50),
    hit int,
    summary varchar(255),
    content varchar(2000),
    source varchar(50),
    editor varchar(50),
    update_date datetime,
    status int,
    constraint pk_news primary key(id),
    constraint fk_news_category_id foreign key(category_id) references a_news_category(id)
);


create table a_news_comment (
    id bigint generated by default as identity(start with 1, increment by 1),
    news_id bigint,
    name varchar(100),
    content varchar(2000),
    username varchar(50),
    update_date datetime,
    status int,
    ip varchar(20),
    constraint pk_news_comment primary key(id),
    constraint fk_news_comment_news_id foreign key(news_id) references a_news(id)
);


create table a_news_tag (
    id bigint generated by default as identity(start with 1, increment by 1),
    name varchar(50),
    the_sort int,
    constraint pk_news_tag primary key(id)
);


create table a_news_newstag (
    news_id bigint,
    newstag_id bigint,
    constraint pk_news_newstag primary key(news_id,newstag_id),
    constraint fk_news_newstag_news_id foreign key(news_id) references a_news(id),
    constraint fk_news_newstag_newstag_id foreign key(newstag_id) references a_news_tag(id)
);

