alter table A_NEWS drop foreign key FK744A3C118F5E23F7;
alter table A_NEWS_CATEGORY drop foreign key FK6567A56CAF1C28CB;
alter table A_NEWS_COMMENT drop foreign key FK5CDABC117E0115E4;
alter table A_NEWS_NEWSTAG drop foreign key FK923EAD997E0115E4;
alter table A_NEWS_NEWSTAG drop foreign key FK923EAD9963BB8EF0;
alter table A_SECURITY_DEPT drop foreign key FK33849C668034938C;
alter table A_SECURITY_MENU drop foreign key FK3388B3808038AAA6;
alter table A_SECURITY_MENU_ROLE drop foreign key FK14BCADD556E5FA71;
alter table A_SECURITY_MENU_ROLE drop foreign key FK14BCADD53D7765D1;
alter table A_SECURITY_RESOURCE_ROLE drop foreign key FK6FD1850656E5FA71;
alter table A_SECURITY_RESOURCE_ROLE drop foreign key FK6FD185064E5B1FF1;
alter table A_SECURITY_ROLE_USER drop foreign key FK83C60473FC10BE51;
alter table A_SECURITY_ROLE_USER drop foreign key FK83C6047356E5FA71;
alter table A_SECURITY_USER drop foreign key FK338C89EC6176F411;
alter table A_TRACKER_ISSUE drop foreign key FK20F791548D35A05B;
drop table if exists A_NEWS;
drop table if exists A_NEWS_CATEGORY;
drop table if exists A_NEWS_COMMENT;
drop table if exists A_NEWS_CONFIG;
drop table if exists A_NEWS_NEWSTAG;
drop table if exists A_NEWS_TAG;
drop table if exists A_SECURITY_DEPT;
drop table if exists A_SECURITY_MENU;
drop table if exists A_SECURITY_MENU_ROLE;
drop table if exists A_SECURITY_RESOURCE;
drop table if exists A_SECURITY_RESOURCE_ROLE;
drop table if exists A_SECURITY_ROLE;
drop table if exists A_SECURITY_ROLE_USER;
drop table if exists A_SECURITY_USER;
drop table if exists A_TRACKER_ISSUE;
drop table if exists A_TRACKER_PROJECT;
create table A_NEWS (ID bigint not null unique, SUBTITLE varchar(100), LINK varchar(100), HIT integer, SUMMARY varchar(255), UPDATE_DATE datetime, NAME varchar(100), CONTENT text, SOURCE varchar(50), IMAGE varchar(50), EDITOR varchar(50), STATUS integer, CATEGORY_ID bigint, primary key (ID));
create table A_NEWS_CATEGORY (ID bigint not null unique, THE_SORT integer, BIT_CODE bigint, CHAR_CODE varchar(255), NAME varchar(50), STATUS integer, PARENT_ID bigint, primary key (ID));
create table A_NEWS_COMMENT (ID bigint not null unique, USERNAME varchar(50), UPDATE_DATE datetime, IP varchar(20), NAME varchar(100), CONTENT text, STATUS integer, NEWS_ID bigint, primary key (ID));
create table A_NEWS_CONFIG (ID bigint not null unique, NEWS_NEED_AUDIT integer, COMMENT_NEED_AUDIT integer, COULD_COMMENT integer, CATEGORY_STRATEGY integer, TEMPLATE_NAME varchar(50), primary key (ID));
create table A_NEWS_NEWSTAG (NEWSTAG_ID bigint not null, NEWS_ID bigint not null, primary key (NEWS_ID, NEWSTAG_ID));
create table A_NEWS_TAG (ID bigint not null unique, THE_SORT integer, NAME varchar(50) not null unique, primary key (ID));
create table A_SECURITY_DEPT (ID bigint not null unique, THE_SORT integer, DESCN varchar(200), NAME varchar(50), PARENT_ID bigint, primary key (ID));
create table A_SECURITY_MENU (ID bigint not null unique, URL varchar(50), THE_SORT integer, QTIP varchar(50), DESCN varchar(200), NAME varchar(50), IMAGE varchar(50), PARENT_ID bigint, primary key (ID));
create table A_SECURITY_MENU_ROLE (MENU_ID bigint not null, ROLE_ID bigint not null, primary key (ROLE_ID, MENU_ID));
create table A_SECURITY_RESOURCE (ID bigint not null unique, DESCN varchar(200), RES_TYPE varchar(50), RES_STRING varchar(200), NAME varchar(50), primary key (ID));
create table A_SECURITY_RESOURCE_ROLE (RESOURCE_ID bigint not null, ROLE_ID bigint not null, primary key (ROLE_ID, RESOURCE_ID));
create table A_SECURITY_ROLE (ID bigint not null unique, DESCN varchar(200), NAME varchar(50) not null unique, primary key (ID));
create table A_SECURITY_ROLE_USER (ROLE_ID bigint not null, USER_ID bigint not null, primary key (USER_ID, ROLE_ID));
create table A_SECURITY_USER (ID bigint not null unique, USERNAME varchar(50), EMAIL varchar(100), DESCN varchar(200), CODE varchar(50), TRUENAME varchar(50), SEX tinyint, BIRTHDAY datetime, TEL varchar(50), MOBILE varchar(50), DUTY varchar(50), PASSWORD varchar(50), STATUS tinyint, DEPT_ID bigint, primary key (ID));
create table A_TRACKER_ISSUE (ID bigint not null unique, UPDATE_DATE datetime, SEVERITY integer, ASSIGN_TO varchar(50), SUBMIT_BY varchar(50), ADD_TIME datetime, NAME varchar(50), PRIORITY integer, FILE varchar(100), CONTENT text, STATUS integer, PROJECT_ID bigint, primary key (ID));
create table A_TRACKER_PROJECT (ID bigint not null unique, SUMMARY text, THE_SORT integer, FOUNDER varchar(50), NAME varchar(100), primary key (ID));
alter table A_NEWS add index FK744A3C118F5E23F7 (CATEGORY_ID), add constraint FK744A3C118F5E23F7 foreign key (CATEGORY_ID) references A_NEWS_CATEGORY (ID);
alter table A_NEWS_CATEGORY add index FK6567A56CAF1C28CB (PARENT_ID), add constraint FK6567A56CAF1C28CB foreign key (PARENT_ID) references A_NEWS_CATEGORY (ID);
alter table A_NEWS_COMMENT add index FK5CDABC117E0115E4 (NEWS_ID), add constraint FK5CDABC117E0115E4 foreign key (NEWS_ID) references A_NEWS (ID);
alter table A_NEWS_NEWSTAG add index FK923EAD997E0115E4 (NEWS_ID), add constraint FK923EAD997E0115E4 foreign key (NEWS_ID) references A_NEWS (ID);
alter table A_NEWS_NEWSTAG add index FK923EAD9963BB8EF0 (NEWSTAG_ID), add constraint FK923EAD9963BB8EF0 foreign key (NEWSTAG_ID) references A_NEWS_TAG (ID);
alter table A_SECURITY_DEPT add index FK33849C668034938C (PARENT_ID), add constraint FK33849C668034938C foreign key (PARENT_ID) references A_SECURITY_DEPT (ID);
alter table A_SECURITY_MENU add index FK3388B3808038AAA6 (PARENT_ID), add constraint FK3388B3808038AAA6 foreign key (PARENT_ID) references A_SECURITY_MENU (ID);
alter table A_SECURITY_MENU_ROLE add index FK14BCADD556E5FA71 (ROLE_ID), add constraint FK14BCADD556E5FA71 foreign key (ROLE_ID) references A_SECURITY_ROLE (ID);
alter table A_SECURITY_MENU_ROLE add index FK14BCADD53D7765D1 (MENU_ID), add constraint FK14BCADD53D7765D1 foreign key (MENU_ID) references A_SECURITY_MENU (ID);
alter table A_SECURITY_RESOURCE_ROLE add index FK6FD1850656E5FA71 (ROLE_ID), add constraint FK6FD1850656E5FA71 foreign key (ROLE_ID) references A_SECURITY_ROLE (ID);
alter table A_SECURITY_RESOURCE_ROLE add index FK6FD185064E5B1FF1 (RESOURCE_ID), add constraint FK6FD185064E5B1FF1 foreign key (RESOURCE_ID) references A_SECURITY_RESOURCE (ID);
alter table A_SECURITY_ROLE_USER add index FK83C60473FC10BE51 (USER_ID), add constraint FK83C60473FC10BE51 foreign key (USER_ID) references A_SECURITY_USER (ID);
alter table A_SECURITY_ROLE_USER add index FK83C6047356E5FA71 (ROLE_ID), add constraint FK83C6047356E5FA71 foreign key (ROLE_ID) references A_SECURITY_ROLE (ID);
alter table A_SECURITY_USER add index FK338C89EC6176F411 (DEPT_ID), add constraint FK338C89EC6176F411 foreign key (DEPT_ID) references A_SECURITY_DEPT (ID);
alter table A_TRACKER_ISSUE add index FK20F791548D35A05B (PROJECT_ID), add constraint FK20F791548D35A05B foreign key (PROJECT_ID) references A_TRACKER_PROJECT (ID);
