alter table A_NEWS drop constraint FK744A3C118F5E23F7;
alter table A_NEWS_CATEGORY drop constraint FK6567A56CAF1C28CB;
alter table A_NEWS_COMMENT drop constraint FK5CDABC117E0115E4;
alter table A_NEWS_NEWSTAG drop constraint FK923EAD997E0115E4;
alter table A_NEWS_NEWSTAG drop constraint FK923EAD9963BB8EF0;
alter table A_SECURITY_DEPT drop constraint FK33849C668034938C;
alter table A_SECURITY_MENU drop constraint FK3388B3808038AAA6;
alter table A_SECURITY_MENU_ROLE drop constraint FK14BCADD556E5FA71;
alter table A_SECURITY_MENU_ROLE drop constraint FK14BCADD53D7765D1;
alter table A_SECURITY_RESOURCE_ROLE drop constraint FK6FD1850656E5FA71;
alter table A_SECURITY_RESOURCE_ROLE drop constraint FK6FD185064E5B1FF1;
alter table A_SECURITY_ROLE_USER drop constraint FK83C60473FC10BE51;
alter table A_SECURITY_ROLE_USER drop constraint FK83C6047356E5FA71;
alter table A_SECURITY_USER drop constraint FK338C89EC6176F411;
alter table A_TRACKER_ISSUE drop constraint FK20F791548D35A05B;
drop table A_NEWS if exists;
drop table A_NEWS_CATEGORY if exists;
drop table A_NEWS_COMMENT if exists;
drop table A_NEWS_CONFIG if exists;
drop table A_NEWS_NEWSTAG if exists;
drop table A_NEWS_TAG if exists;
drop table A_SECURITY_DEPT if exists;
drop table A_SECURITY_MENU if exists;
drop table A_SECURITY_MENU_ROLE if exists;
drop table A_SECURITY_RESOURCE if exists;
drop table A_SECURITY_RESOURCE_ROLE if exists;
drop table A_SECURITY_ROLE if exists;
drop table A_SECURITY_ROLE_USER if exists;
drop table A_SECURITY_USER if exists;
drop table A_TRACKER_ISSUE if exists;
drop table A_TRACKER_PROJECT if exists;
create table A_NEWS (ID bigint not null, SUBTITLE varchar(100), LINK varchar(100), HIT integer, SUMMARY varchar(255), UPDATE_DATE timestamp, NAME varchar(100), CONTENT longvarchar, SOURCE varchar(50), IMAGE varchar(50), EDITOR varchar(50), STATUS integer, CATEGORY_ID bigint, primary key (ID), unique (ID));
create table A_NEWS_CATEGORY (ID bigint not null, THE_SORT integer, BIT_CODE bigint, CHAR_CODE varchar(255), NAME varchar(50), STATUS integer, PARENT_ID bigint, primary key (ID), unique (ID));
create table A_NEWS_COMMENT (ID bigint not null, USERNAME varchar(50), UPDATE_DATE timestamp, IP varchar(20), NAME varchar(100), CONTENT longvarchar, STATUS integer, NEWS_ID bigint, primary key (ID), unique (ID));
create table A_NEWS_CONFIG (ID bigint not null, NEWS_NEED_AUDIT integer, COMMENT_NEED_AUDIT integer, COULD_COMMENT integer, CATEGORY_STRATEGY integer, TEMPLATE_NAME varchar(50), primary key (ID), unique (ID));
create table A_NEWS_NEWSTAG (NEWSTAG_ID bigint not null, NEWS_ID bigint not null, primary key (NEWS_ID, NEWSTAG_ID));
create table A_NEWS_TAG (ID bigint not null, THE_SORT integer, NAME varchar(50) not null, primary key (ID), unique (ID), unique (NAME));
create table A_SECURITY_DEPT (ID bigint not null, THE_SORT integer, DESCN varchar(200), NAME varchar(50), PARENT_ID bigint, primary key (ID), unique (ID));
create table A_SECURITY_MENU (ID bigint not null, URL varchar(50), THE_SORT integer, QTIP varchar(50), DESCN varchar(200), NAME varchar(50), IMAGE varchar(50), PARENT_ID bigint, primary key (ID), unique (ID));
create table A_SECURITY_MENU_ROLE (MENU_ID bigint not null, ROLE_ID bigint not null, primary key (ROLE_ID, MENU_ID));
create table A_SECURITY_RESOURCE (ID bigint not null, DESCN varchar(200), RES_TYPE varchar(50), RES_STRING varchar(200), NAME varchar(50), primary key (ID), unique (ID));
create table A_SECURITY_RESOURCE_ROLE (RESOURCE_ID bigint not null, ROLE_ID bigint not null, primary key (ROLE_ID, RESOURCE_ID));
create table A_SECURITY_ROLE (ID bigint not null, DESCN varchar(200), NAME varchar(50) not null, primary key (ID), unique (ID), unique (NAME));
create table A_SECURITY_ROLE_USER (ROLE_ID bigint not null, USER_ID bigint not null, primary key (USER_ID, ROLE_ID));
create table A_SECURITY_USER (ID bigint not null, USERNAME varchar(50), EMAIL varchar(100), DESCN varchar(200), CODE varchar(50), TRUENAME varchar(50), SEX tinyint, BIRTHDAY timestamp, TEL varchar(50), MOBILE varchar(50), DUTY varchar(50), PASSWORD varchar(50), STATUS tinyint, DEPT_ID bigint, primary key (ID), unique (ID));
create table A_TRACKER_ISSUE (ID bigint not null, UPDATE_DATE timestamp, SEVERITY integer, ASSIGN_TO varchar(50), SUBMIT_BY varchar(50), ADD_TIME timestamp, NAME varchar(50), PRIORITY integer, FILE varchar(100), CONTENT longvarchar, STATUS integer, PROJECT_ID bigint, primary key (ID), unique (ID));
create table A_TRACKER_PROJECT (ID bigint not null, SUMMARY longvarchar, THE_SORT integer, FOUNDER varchar(50), NAME varchar(100), primary key (ID), unique (ID));
alter table A_NEWS add constraint FK744A3C118F5E23F7 foreign key (CATEGORY_ID) references A_NEWS_CATEGORY;
alter table A_NEWS_CATEGORY add constraint FK6567A56CAF1C28CB foreign key (PARENT_ID) references A_NEWS_CATEGORY;
alter table A_NEWS_COMMENT add constraint FK5CDABC117E0115E4 foreign key (NEWS_ID) references A_NEWS;
alter table A_NEWS_NEWSTAG add constraint FK923EAD997E0115E4 foreign key (NEWS_ID) references A_NEWS;
alter table A_NEWS_NEWSTAG add constraint FK923EAD9963BB8EF0 foreign key (NEWSTAG_ID) references A_NEWS_TAG;
alter table A_SECURITY_DEPT add constraint FK33849C668034938C foreign key (PARENT_ID) references A_SECURITY_DEPT;
alter table A_SECURITY_MENU add constraint FK3388B3808038AAA6 foreign key (PARENT_ID) references A_SECURITY_MENU;
alter table A_SECURITY_MENU_ROLE add constraint FK14BCADD556E5FA71 foreign key (ROLE_ID) references A_SECURITY_ROLE;
alter table A_SECURITY_MENU_ROLE add constraint FK14BCADD53D7765D1 foreign key (MENU_ID) references A_SECURITY_MENU;
alter table A_SECURITY_RESOURCE_ROLE add constraint FK6FD1850656E5FA71 foreign key (ROLE_ID) references A_SECURITY_ROLE;
alter table A_SECURITY_RESOURCE_ROLE add constraint FK6FD185064E5B1FF1 foreign key (RESOURCE_ID) references A_SECURITY_RESOURCE;
alter table A_SECURITY_ROLE_USER add constraint FK83C60473FC10BE51 foreign key (USER_ID) references A_SECURITY_USER;
alter table A_SECURITY_ROLE_USER add constraint FK83C6047356E5FA71 foreign key (ROLE_ID) references A_SECURITY_ROLE;
alter table A_SECURITY_USER add constraint FK338C89EC6176F411 foreign key (DEPT_ID) references A_SECURITY_DEPT;
alter table A_TRACKER_ISSUE add constraint FK20F791548D35A05B foreign key (PROJECT_ID) references A_TRACKER_PROJECT;
