package anni.aerp.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * ErpOrderInfo generated by Lingo.
 *
 * @author Lingo
 * @since 2007年10月25日 下午 22时39分57秒125
 */
@Entity
@Table(name = "A_ERP_ORDER_INFO")
public class ErpOrderInfo extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * erpOrder. */
    private ErpOrder erpOrder;

    /** * product. */
    private String product;

    /** * type. */
    private String type;

    /** * unit. */
    private String unit;

    /** * width. */
    private String width;

    /** * height. */
    private String height;

    /** * area. */
    private String area;

    /** * price. */
    private String price;

    /** * amount. */
    private String amount;

    /** * num. */
    private String num;

    /** * unitType. */
    private String unitType;

    /** * status. */
    private String status;

    /** * 构造方法. */
    public ErpOrderInfo() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return erpOrder. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ORDER_ID")
    public ErpOrder getErpOrder() {
        return erpOrder;
    }

    /** * @param erpOrder ErpOrder. */
    public void setErpOrder(ErpOrder erpOrder) {
        this.erpOrder = erpOrder;
    }

    /** * @return product. */
    @Column(name = "PRODUCT", length = 50)
    public String getProduct() {
        return product;
    }

    /** * @param product String. */
    public void setProduct(String product) {
        this.product = product;
    }

    /** * @return type. */
    @Column(name = "TYPE", length = 50)
    public String getType() {
        return type;
    }

    /** * @param type String. */
    public void setType(String type) {
        this.type = type;
    }

    /** * @return unit. */
    @Column(name = "UNIT", length = 50)
    public String getUnit() {
        return unit;
    }

    /** * @param unit String. */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /** * @return width. */
    @Column(name = "WIDTH", length = 50)
    public String getWidth() {
        return width;
    }

    /** * @param width String. */
    public void setWidth(String width) {
        this.width = width;
    }

    /** * @return height. */
    @Column(name = "HEIGHT", length = 50)
    public String getHeight() {
        return height;
    }

    /** * @param height String. */
    public void setHeight(String height) {
        this.height = height;
    }

    /** * @return area. */
    @Column(name = "AREA", length = 50)
    public String getArea() {
        return area;
    }

    /** * @param area String. */
    public void setArea(String area) {
        this.area = area;
    }

    /** * @return price. */
    @Column(name = "PRICE", length = 50)
    public String getPrice() {
        return price;
    }

    /** * @param price String. */
    public void setPrice(String price) {
        this.price = price;
    }

    /** * @return amount. */
    @Column(name = "AMOUNT", length = 50)
    public String getAmount() {
        return amount;
    }

    /** * @param amount String. */
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /** * @return num. */
    @Column(name = "NUM", length = 50)
    public String getNum() {
        return num;
    }

    /** * @param num String. */
    public void setNum(String num) {
        this.num = num;
    }

    /** * @return unitType. */
    @Column(name = "UNIT_TYPE", length = 50)
    public String getUnitType() {
        return unitType;
    }

    /** * @param unitType String. */
    public void setUnitType(String unitType) {
        this.unitType = unitType;
    }

    /** * @return status. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return status;
    }

    /** * @param status String. */
    public void setStatus(String status) {
        this.status = status;
    }
}
