package anni.aerp.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * ErpRation generated by Lingo.
 *
 * @author Lingo
 * @since 2007年10月25日 下午 22时23分30秒750
 */
@Entity
@Table(name = "A_ERP_RATION")
public class ErpRation extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * product. */
    private String product;

    /** * material. */
    private String material;

    /** * rate. */
    private String rate;

    /** * unit. */
    private String unit;

    /** * status. */
    private String status;

    /** * descn. */
    private String descn;

    /** * inputMan. */
    private String inputMan;

    /** * inputTime. */
    private Date inputTime;

    /** * 构造方法. */
    public ErpRation() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return product. */
    @Column(name = "PRODUCT", length = 50)
    public String getProduct() {
        return product;
    }

    /** * @param product String. */
    public void setProduct(String product) {
        this.product = product;
    }

    /** * @return material. */
    @Column(name = "MATERIAL", length = 50)
    public String getMaterial() {
        return material;
    }

    /** * @param material String. */
    public void setMaterial(String material) {
        this.material = material;
    }

    /** * @return rate. */
    @Column(name = "RATE", length = 50)
    public String getRate() {
        return rate;
    }

    /** * @param rate String. */
    public void setRate(String rate) {
        this.rate = rate;
    }

    /** * @return unit. */
    @Column(name = "UNIT", length = 50)
    public String getUnit() {
        return unit;
    }

    /** * @param unit String. */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /** * @return status. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return status;
    }

    /** * @param status String. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** * @return descn. */
    @Column(name = "DESCN", length = 2000)
    @Lob
    public String getDescn() {
        return descn;
    }

    /** * @param descn String. */
    public void setDescn(String descn) {
        this.descn = descn;
    }

    /** * @return inputMan. */
    @Column(name = "INPUT_MAN", length = 50)
    public String getInputMan() {
        return inputMan;
    }

    /** * @param inputMan String. */
    public void setInputMan(String inputMan) {
        this.inputMan = inputMan;
    }

    /** * @return inputTime. */
    @Column(name = "INPUT_TIME")
    public Date getInputTime() {
        if (inputTime != null) {
            return (Date) inputTime.clone();
        } else {
            return null;
        }
    }

    /** * @param inputTime Date. */
    public void setInputTime(Date inputTime) {
        if (inputTime == null) {
            this.inputTime = null;
        } else {
            this.inputTime = (Date) inputTime.clone();
        }
    }
}
