package anni.aerp2.domain;

import java.io.Serializable;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * Erp2SuccessBid generated by Lingo.
 *
 * @author Lingo
 * @since 2007年11月08日 上午 01时50分13秒93
 */
@Entity
@Table(name = "A_ERP2_SUCCESS_BID")
public class Erp2SuccessBid extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * erp2InviteBid. */
    private Erp2InviteBid erp2InviteBid;

    /** * publishDate. */
    private Date publishDate;

    /** * bidContent. */
    private String bidContent;

    /** * price. */
    private Double price;

    /** * descn. */
    private String descn;

    /** * 构造方法. */
    public Erp2SuccessBid() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return erp2InviteBid. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INVITE_BID_ID")
    public Erp2InviteBid getErp2InviteBid() {
        return erp2InviteBid;
    }

    /** * @param erp2InviteBid Erp2InviteBid. */
    public void setErp2InviteBid(Erp2InviteBid erp2InviteBid) {
        this.erp2InviteBid = erp2InviteBid;
    }

    /** * @return publishDate. */
    @Column(name = "PUBLISH_DATE")
    public Date getPublishDate() {
        return publishDate;
    }

    /** * @param publishDate Date. */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /** * @return bidContent. */
    @Column(name = "BID_CONTENT", length = 50)
    public String getBidContent() {
        return bidContent;
    }

    /** * @param bidContent String. */
    public void setBidContent(String bidContent) {
        this.bidContent = bidContent;
    }

    /** * @return price. */
    @Column(name = "PRICE")
    public Double getPrice() {
        return price;
    }

    /** * @param price Double. */
    public void setPrice(Double price) {
        this.price = price;
    }

    /** * @return descn. */
    @Column(name = "DESCN", length = 2000)
    @Lob
    public String getDescn() {
        return descn;
    }

    /** * @param descn String. */
    public void setDescn(String descn) {
        this.descn = descn;
    }
}
