package anni.aerp2.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * Erp2BuyContract generated by Lingo.
 *
 * @author Lingo
 * @since 2007年11月12日 上午 02时32分13秒453
 */
@Entity
@Table(name = "A_ERP2_BUY_CONTRACT")
public class Erp2BuyContract extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * erp2Supplier. */
    private Erp2Supplier erp2Supplier;

    /** * code. */
    private String code;

    /** * status. */
    private String status;

    /** * name. */
    private String name;

    /** * linkman. */
    private String linkman;

    /** * provideDate. */
    private Date provideDate;

    /** * receipt. */
    private String receipt;

    /** * contractDate. */
    private Date contractDate;

    /** * username. */
    private String username;

    /** * 构造方法. */
    public Erp2BuyContract() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return erp2Supplier. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "SUPPLIER_ID")
    public Erp2Supplier getErp2Supplier() {
        return erp2Supplier;
    }

    /** * @param erp2Supplier Erp2Supplier. */
    public void setErp2Supplier(Erp2Supplier erp2Supplier) {
        this.erp2Supplier = erp2Supplier;
    }

    /** * @return code. */
    @Column(name = "CODE", length = 50)
    public String getCode() {
        return code;
    }

    /** * @param code String. */
    public void setCode(String code) {
        this.code = code;
    }

    /** * @return status. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return status;
    }

    /** * @param status String. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** * @return name. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return name;
    }

    /** * @param name String. */
    public void setName(String name) {
        this.name = name;
    }

    /** * @return linkman. */
    @Column(name = "LINKMAN", length = 50)
    public String getLinkman() {
        return linkman;
    }

    /** * @param linkman String. */
    public void setLinkman(String linkman) {
        this.linkman = linkman;
    }

    /** * @return provideDate. */
    @Column(name = "PROVIDE_DATE")
    public Date getProvideDate() {
        return provideDate;
    }

    /** * @param provideDate Date. */
    public void setProvideDate(Date provideDate) {
        this.provideDate = provideDate;
    }

    /** * @return receipt. */
    @Column(name = "RECEIPT", length = 50)
    public String getReceipt() {
        return receipt;
    }

    /** * @param receipt String. */
    public void setReceipt(String receipt) {
        this.receipt = receipt;
    }

    /** * @return contractDate. */
    @Column(name = "CONTRACT_DATE")
    public Date getContractDate() {
        return contractDate;
    }

    /** * @param contractDate Date. */
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    /** * @return username. */
    @Column(name = "USERNAME", length = 50)
    public String getUsername() {
        return username;
    }

    /** * @param username String. */
    public void setUsername(String username) {
        this.username = username;
    }
}
