package anni.aerp.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * ErpMaterial generated by Lingo.
 *
 * @author Lingo
 * @since 2007年10月25日 下午 22时23分30秒750
 */
@Entity
@Table(name = "A_ERP_MATERIAL")
public class ErpMaterial extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * name. */
    private String name;

    /** * source. */
    private String source;

    /** * supplier. */
    private String supplier;

    /** * price. */
    private Double price;

    /** * unit. */
    private String unit;

    /** * status. */
    private String status;

    /** * descn. */
    private String descn;

    /** * inputMan. */
    private String inputMan;

    /** * inputTime. */
    private Date inputTime;

    /** * 构造方法. */
    public ErpMaterial() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return name. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return name;
    }

    /** * @param name String. */
    public void setName(String name) {
        this.name = name;
    }

    /** * @return source. */
    @Column(name = "SOURCE", length = 50)
    public String getSource() {
        return source;
    }

    /** * @param source String. */
    public void setSource(String source) {
        this.source = source;
    }

    /** * @return supplier. */
    @Column(name = "SUPPLIER", length = 50)
    public String getSupplier() {
        return supplier;
    }

    /** * @param supplier String. */
    public void setSupplier(String supplier) {
        this.supplier = supplier;
    }

    /** * @return price. */
    @Column(name = "PRICE")
    public Double getPrice() {
        return price;
    }

    /** * @param price Double. */
    public void setPrice(Double price) {
        this.price = price;
    }

    /** * @return unit. */
    @Column(name = "UNIT", length = 50)
    public String getUnit() {
        return unit;
    }

    /** * @param unit String. */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /** * @return status. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return status;
    }

    /** * @param status String. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** * @return descn. */
    @Column(name = "DESCN", length = 2000)
    @Lob
    public String getDescn() {
        return descn;
    }

    /** * @param descn String. */
    public void setDescn(String descn) {
        this.descn = descn;
    }

    /** * @return inputMan. */
    @Column(name = "INPUT_MAN", length = 50)
    public String getInputMan() {
        return inputMan;
    }

    /** * @param inputMan String. */
    public void setInputMan(String inputMan) {
        this.inputMan = inputMan;
    }

    /** * @return inputTime. */
    @Column(name = "INPUT_TIME")
    public Date getInputTime() {
        if (inputTime != null) {
            return (Date) inputTime.clone();
        } else {
            return null;
        }
    }

    /** * @param inputTime Date. */
    public void setInputTime(Date inputTime) {
        if (inputTime == null) {
            this.inputTime = null;
        } else {
            this.inputTime = (Date) inputTime.clone();
        }
    }
}
