package anni.aerp.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * ErpProduct generated by Lingo.
 *
 * @author Lingo
 * @since 2007年10月25日 下午 22时23分30秒750
 */
@Entity
@Table(name = "A_ERP_PRODUCT")
public class ErpProduct extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * name. */
    private String name;

    /** * code. */
    private String code;

    /** * type. */
    private String type;

    /** * buyPrice. */
    private Double buyPrice;

    /** * salePrice. */
    private Double salePrice;

    /** * unit. */
    private String unit;

    /** * pic. */
    private String pic;

    /** * status. */
    private String status;

    /** * descn. */
    private String descn;

    /** * inputMan. */
    private String inputMan;

    /** * inputTime. */
    private Date inputTime;

    /** * 构造方法. */
    public ErpProduct() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return name. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return name;
    }

    /** * @param name String. */
    public void setName(String name) {
        this.name = name;
    }

    /** * @return code. */
    @Column(name = "CODE", length = 50)
    public String getCode() {
        return code;
    }

    /** * @param code String. */
    public void setCode(String code) {
        this.code = code;
    }

    /** * @return type. */
    @Column(name = "TYPE", length = 50)
    public String getType() {
        return type;
    }

    /** * @param type String. */
    public void setType(String type) {
        this.type = type;
    }

    /** * @return buyPrice. */
    @Column(name = "BUY_PRICE")
    public Double getBuyPrice() {
        return buyPrice;
    }

    /** * @param buyPrice Double. */
    public void setBuyPrice(Double buyPrice) {
        this.buyPrice = buyPrice;
    }

    /** * @return salePrice. */
    @Column(name = "SALE_PRICE")
    public Double getSalePrice() {
        return salePrice;
    }

    /** * @param salePrice Double. */
    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    /** * @return unit. */
    @Column(name = "UNIT", length = 50)
    public String getUnit() {
        return unit;
    }

    /** * @param unit String. */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /** * @return pic. */
    @Column(name = "PIC", length = 50)
    public String getPic() {
        return pic;
    }

    /** * @param pic String. */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /** * @return status. */
    @Column(name = "STATUS", length = 50)
    public String getStatus() {
        return status;
    }

    /** * @param status String. */
    public void setStatus(String status) {
        this.status = status;
    }

    /** * @return descn. */
    @Column(name = "DESCN", length = 2000)
    @Lob
    public String getDescn() {
        return descn;
    }

    /** * @param descn String. */
    public void setDescn(String descn) {
        this.descn = descn;
    }

    /** * @return inputMan. */
    @Column(name = "INPUT_MAN", length = 50)
    public String getInputMan() {
        return inputMan;
    }

    /** * @param inputMan String. */
    public void setInputMan(String inputMan) {
        this.inputMan = inputMan;
    }

    /** * @return inputTime. */
    @Column(name = "INPUT_TIME")
    public Date getInputTime() {
        if (inputTime != null) {
            return (Date) inputTime.clone();
        } else {
            return null;
        }
    }

    /** * @param inputTime Date. */
    public void setInputTime(Date inputTime) {
        if (inputTime == null) {
            this.inputTime = null;
        } else {
            this.inputTime = (Date) inputTime.clone();
        }
    }
}
