package anni.anews.domain;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

import anni.core.domain.tree.AbstractTreeEntityBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * Category generated by Lingo.
 *
 * @author Lingo
 * @since 2007年08月08日 下午 18时10分00秒750
 */
@Entity
@Table(name = "A_NEWS_CATEGORY")
public class Category extends AbstractTreeEntityBean<Category> {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * top category. */
    private Category top;

    /** * parent category. */
    private Category parent;

    /** * name. */
    private String name;

    /** * theSort. */
    private Integer theSort;

    /** * status. */
    private Integer status;

    /** * all children. */
    private Set<Category> allChildren = new HashSet<Category>(0);

    /** * children. */
    private Set<Category> children = new HashSet<Category>(0);

    /** * newses. */
    private Set<News> newses = new HashSet<News>(0);

    /** * 构造方法. */
    public Category() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id id. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return top category. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TOP_ID")
    public Category getTop() {
        return top;
    }

    /** * @param top Top Catgegory. */
    public void setTop(Category top) {
        this.top = top;
    }

    /** * @return categoryByParentId. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PARENT_ID")
    public Category getParent() {
        return parent;
    }

    /** * @param parent parent. */
    public void setParent(Category parent) {
        this.parent = parent;
    }

    /** * @return name. */
    @Column(name = "NAME", length = 50)
    public String getName() {
        return name;
    }

    /** * @param name name. */
    public void setName(String name) {
        this.name = name;
    }

    /** * @return theSort. */
    @Column(name = "THE_SORT")
    public Integer getTheSort() {
        return theSort;
    }

    /** * @param theSort theSort. */
    public void setTheSort(Integer theSort) {
        this.theSort = theSort;
    }

    /** * @return status. */
    @Column(name = "STATUS")
    public Integer getStatus() {
        return status;
    }

    /** * @param status status. */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /** * @return categoriesForTopId. */
    @OrderBy("theSort asc,id desc")
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "top")
    public Set<Category> getAllChildren() {
        return allChildren;
    }

    /** * @param allChildren allChildren. */
    public void setAllChildren(Set<Category> allChildren) {
        this.allChildren = allChildren;
    }

    /** * @return children. */
    @OrderBy("theSort asc,id desc")
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "parent")
    public Set<Category> getChildren() {
        return children;
    }

    /** * @param children children. */
    public void setChildren(Set<Category> children) {
        this.children = children;
    }

    /** * @return newses. */
    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "category")
    public Set<News> getNewses() {
        return newses;
    }

    /** * @param newses newses. */
    public void setNewses(Set<News> newses) {
        this.newses = newses;
    }
}
