package anni.aerp2.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import anni.core.grid.LongGridBean;

import org.hibernate.annotations.GenericGenerator;


/**
 * Erp2BuyOrderInfo generated by Lingo.
 *
 * @author Lingo
 * @since 2007年11月11日 下午 23时13分40秒890
 */
@Entity
@Table(name = "A_ERP2_BUY_ORDER_INFO")
public class Erp2BuyOrderInfo extends LongGridBean {
    /** * serial. */
    static final long serialVersionUID = 0L;

    /** * id. */
    private Long id;

    /** * erp2Product. */
    private Erp2Product erp2Product;

    /** * erp2BuyOrder. */
    private Erp2BuyOrder erp2BuyOrder;

    /** * code. */
    private String code;

    /** * parameter. */
    private String parameter;

    /** * num. */
    private Integer num;

    /** * price. */
    private Double price;

    /** * totalPrice. */
    private Double totalPrice;

    /** * descn. */
    private String descn;

    /** * 构造方法. */
    public Erp2BuyOrderInfo() {
    }

    /** * @return id. */
    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return id;
    }

    /** * @param id Long. */
    public void setId(Long id) {
        this.id = id;
    }

    /** * @return erp2Product. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PRODUCT_ID")
    public Erp2Product getErp2Product() {
        return erp2Product;
    }

    /** * @param erp2Product Erp2Product. */
    public void setErp2Product(Erp2Product erp2Product) {
        this.erp2Product = erp2Product;
    }

    /** * @return erp2BuyOrder. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BUY_ORDER_ID")
    public Erp2BuyOrder getErp2BuyOrder() {
        return erp2BuyOrder;
    }

    /** * @param erp2BuyOrder Erp2BuyOrder. */
    public void setErp2BuyOrder(Erp2BuyOrder erp2BuyOrder) {
        this.erp2BuyOrder = erp2BuyOrder;
    }

    /** * @return code. */
    @Column(name = "CODE", length = 50)
    public String getCode() {
        return code;
    }

    /** * @param code String. */
    public void setCode(String code) {
        this.code = code;
    }

    /** * @return parameter. */
    @Column(name = "PARAMETER", length = 50)
    public String getParameter() {
        return parameter;
    }

    /** * @param parameter String. */
    public void setParameter(String parameter) {
        this.parameter = parameter;
    }

    /** * @return num. */
    @Column(name = "NUM")
    public Integer getNum() {
        return num;
    }

    /** * @param num Integer. */
    public void setNum(Integer num) {
        this.num = num;
    }

    /** * @return price. */
    @Column(name = "PRICE")
    public Double getPrice() {
        return price;
    }

    /** * @param price Double. */
    public void setPrice(Double price) {
        this.price = price;
    }

    /** * @return totalPrice. */
    @Column(name = "TOTAL_PRICE")
    public Double getTotalPrice() {
        return totalPrice;
    }

    /** * @param totalPrice Double. */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /** * @return descn. */
    @Column(name = "DESCN", length = 2000)
    @Lob
    public String getDescn() {
        return descn;
    }

    /** * @param descn String. */
    public void setDescn(String descn) {
        this.descn = descn;
    }
}
