package anni.core.mock.db.domain;


// Generated 2007-7-11 22:14:50 by Hibernate Tools 3.2.0.b9
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;


/**
 * Dictionary generated by hbm2java
 */
@Entity
@Table(name = "DICTIONARY", schema = "PUBLIC")
public class Dictionary implements java.io.Serializable {
    /** * serial. */
    static final long serialVersionUID = 0L;
    private Long id;
    private String name;

    public Dictionary() {
    }

    public Dictionary(String name) {
        this.name = name;
    }

    @GenericGenerator(name = "generator", strategy = "increment")
    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "NAME", length = 50)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
